# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonUiHtmxNightly < Formula
  desc "Server-rendered web configuration UI (BFF) for rusty-photon — HTMX expression"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607200814.g547f38f"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-ui-htmx-0.1.0+nightly.202607200814.g547f38f-aarch64-apple-darwin.tar.gz"
  sha256 "d93d53a1b996409c6b3c1d8a4324548859b45f6f9bc5ef32020066fc0ece4826"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-ui-htmx",
    because: "both channels install the same rusty-photon-ui-htmx binary"

  def install
    bin.install "rusty-photon-ui-htmx"
  end

  service do
    run [opt_bin/"rusty-photon-ui-htmx"]
    keep_alive true
    log_path var/"log/rusty-photon-ui-htmx.log"
    error_log_path var/"log/rusty-photon-ui-htmx.log"
  end

  test do
    assert_match "ui-htmx", shell_output("#{bin}/rusty-photon-ui-htmx --help")
  end
end
