# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonZwoCameraNightly < Formula
  desc "ASCOM Alpaca Camera (+ EFW FilterWheel) driver for ZWO ASI hardware"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607300739.g05d74aa"
  license all_of: [{ any_of: ["MIT", "Apache-2.0"] }, "MIT"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-zwo-camera-0.1.0+nightly.202607300739.g05d74aa-aarch64-apple-darwin.tar.gz"
  sha256 "d2f59c9828a3d837f56e48dd0237e923c5c4b265f1621a860e3fd7676f0ec98d"

  depends_on :macos
  depends_on arch: :arm64
  depends_on "libusb"

  conflicts_with "rusty-photon-zwo-camera",
    because: "both channels install the same rusty-photon-zwo-camera binary"

  def install
    bin.install "rusty-photon-zwo-camera"
    lib.install Dir["lib/*.dylib"]
    doc.install "ZWO-SDK-LICENSE.txt"
  end

  service do
    run [opt_bin/"rusty-photon-zwo-camera"]
    keep_alive true
    log_path var/"log/rusty-photon-zwo-camera.log"
    error_log_path var/"log/rusty-photon-zwo-camera.log"
  end

  test do
    assert_match "zwo-camera", shell_output("#{bin}/rusty-photon-zwo-camera --help")
  end
end
