# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonSentinelNightly < Formula
  desc "Observatory monitoring and notification service"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.20260716.g812bbf6"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-sentinel-0.1.0+nightly.20260716.g812bbf6-aarch64-apple-darwin.tar.gz"
  sha256 "01d9011bb6c512aa421cbb04c7fff80bb5c4bd3b15f18b2f40914b6b2bbcb24b"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-sentinel",
    because: "both channels install the same rusty-photon-sentinel binary"

  def install
    bin.install "rusty-photon-sentinel"
  end

  service do
    run [opt_bin/"rusty-photon-sentinel"]
    keep_alive true
    log_path var/"log/rusty-photon-sentinel.log"
    error_log_path var/"log/rusty-photon-sentinel.log"
  end

  test do
    assert_match "sentinel", shell_output("#{bin}/rusty-photon-sentinel --help")
  end
end
