# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonRpNightly < Formula
  desc "Rusty Photon main application - equipment gateway, event bus, and safety enforcer"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607200814.g547f38f"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-rp-0.1.0+nightly.202607200814.g547f38f-aarch64-apple-darwin.tar.gz"
  sha256 "0fd96f80880faaf7050cd69c408c26fe883b2f1508e84b29062dee6b5255f47e"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-rp",
    because: "both channels install the same rusty-photon-rp binary"

  def install
    bin.install "rusty-photon-rp"
  end

  service do
    run [opt_bin/"rusty-photon-rp"]
    keep_alive true
    log_path var/"log/rusty-photon-rp.log"
    error_log_path var/"log/rusty-photon-rp.log"
  end

  test do
    assert_match "rp", shell_output("#{bin}/rusty-photon-rp --help")
  end
end
