# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPaScopsOagNightly < Formula
  desc "ASCOM Alpaca driver for the Pegasus Astro Scops OAG focuser"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202608140622.g3141e25"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-pa-scops-oag-0.1.0+nightly.202608140622.g3141e25-aarch64-apple-darwin.tar.gz"
  sha256 "f5587125eb048e1d0ab539663be114e810542db7f585e4abdcdc95b6252ec733"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-pa-scops-oag",
    because: "both channels install the same rusty-photon-pa-scops-oag binary"

  def install
    bin.install "rusty-photon-pa-scops-oag"
  end

  service do
    run [opt_bin/"rusty-photon-pa-scops-oag"]
    keep_alive true
    log_path var/"log/rusty-photon-pa-scops-oag.log"
    error_log_path var/"log/rusty-photon-pa-scops-oag.log"
  end

  test do
    assert_match "pa-scops-oag", shell_output("#{bin}/rusty-photon-pa-scops-oag --help")
  end
end
