# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonDsdFp2Nightly < Formula
  desc "ASCOM Alpaca CoverCalibrator driver for the Deep Sky Dad Flat Panel 2 (FP2)"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607210739.g267e4e6"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-dsd-fp2-0.1.0+nightly.202607210739.g267e4e6-aarch64-apple-darwin.tar.gz"
  sha256 "6221eeb160a27c53c090fca8fee8dc865e6691675057e222d5a17d5438813e1d"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-dsd-fp2",
    because: "both channels install the same rusty-photon-dsd-fp2 binary"

  def install
    bin.install "rusty-photon-dsd-fp2"
  end

  service do
    run [opt_bin/"rusty-photon-dsd-fp2"]
    keep_alive true
    log_path var/"log/rusty-photon-dsd-fp2.log"
    error_log_path var/"log/rusty-photon-dsd-fp2.log"
  end

  test do
    assert_match "dsd-fp2", shell_output("#{bin}/rusty-photon-dsd-fp2 --help")
  end
end
