# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonStarAdventurerGtiNightly < Formula
  desc "ASCOM Alpaca driver for Sky-Watcher Star Adventurer GTi GEM"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607190022.g5f191ee"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-star-adventurer-gti-0.1.0+nightly.202607190022.g5f191ee-aarch64-apple-darwin.tar.gz"
  sha256 "2f165887f8237ae0961183def186d88e369f2ff6d6935d5d7559107e56a119d6"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-star-adventurer-gti",
    because: "both channels install the same rusty-photon-star-adventurer-gti binary"

  def install
    bin.install "rusty-photon-star-adventurer-gti"
  end

  service do
    run [opt_bin/"rusty-photon-star-adventurer-gti"]
    keep_alive true
    log_path var/"log/rusty-photon-star-adventurer-gti.log"
    error_log_path var/"log/rusty-photon-star-adventurer-gti.log"
  end

  test do
    assert_match "star-adventurer-gti", shell_output("#{bin}/rusty-photon-star-adventurer-gti --help")
  end
end
