# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPlateSolverNightly < Formula
  desc "rp-managed plate solver service: HTTP wrapper around the ASTAP CLI"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.20260718.g6f89442"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-plate-solver-0.1.0+nightly.20260718.g6f89442-aarch64-apple-darwin.tar.gz"
  sha256 "0cdb0062321c504555ef4fac4e3e2a23e4ee0ef3f8f3a07461fb6db2a1e694d2"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-plate-solver",
    because: "both channels install the same rusty-photon-plate-solver binary"

  def install
    bin.install "rusty-photon-plate-solver"
  end

  service do
    run [opt_bin/"rusty-photon-plate-solver"]
    keep_alive true
    log_path var/"log/rusty-photon-plate-solver.log"
    error_log_path var/"log/rusty-photon-plate-solver.log"
  end

  test do
    assert_match "plate-solver", shell_output("#{bin}/rusty-photon-plate-solver --help")
  end
end
