# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonQhyFocuserNightly < Formula
  desc "ASCOM Alpaca driver for QHY Q-Focuser (EAF)"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607191553.g30a7144"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-qhy-focuser-0.1.0+nightly.202607191553.g30a7144-aarch64-apple-darwin.tar.gz"
  sha256 "b8642c92dc75b65eef158004ffa988a5c65ea555ce266c633850357415960477"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-qhy-focuser",
    because: "both channels install the same rusty-photon-qhy-focuser binary"

  def install
    bin.install "rusty-photon-qhy-focuser"
  end

  service do
    run [opt_bin/"rusty-photon-qhy-focuser"]
    keep_alive true
    log_path var/"log/rusty-photon-qhy-focuser.log"
    error_log_path var/"log/rusty-photon-qhy-focuser.log"
  end

  test do
    assert_match "qhy-focuser", shell_output("#{bin}/rusty-photon-qhy-focuser --help")
  end
end
