# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonNightly < Formula
  desc "Rusty Photon astrophotography service family (every service)"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607300739.g05d74aa"
  license any_of: ["MIT", "Apache-2.0"]
  # A formula must download something; the channel's checksum manifest is
  # the natural tiny asset for a meta-formula that only pulls dependencies.
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/SHA256SUMS.txt"
  sha256 "133a5011f60b2d8aa4a682b8ee71a4f95efa25064b262627a684b052100fab64"

  depends_on :macos
  depends_on arch: :arm64
  depends_on "rusty-photon-calibrator-flats-nightly"
  depends_on "rusty-photon-dsd-fp2-nightly"
  depends_on "rusty-photon-filemonitor-nightly"
  depends_on "rusty-photon-pa-falcon-rotator-nightly"
  depends_on "rusty-photon-pa-scops-oag-nightly"
  depends_on "rusty-photon-phd2-guider-nightly"
  depends_on "rusty-photon-plate-solver-nightly"
  depends_on "rusty-photon-ppba-driver-nightly"
  depends_on "rusty-photon-qhy-camera-nightly"
  depends_on "rusty-photon-qhy-focuser-nightly"
  depends_on "rusty-photon-rp-nightly"
  depends_on "rusty-photon-sentinel-nightly"
  depends_on "rusty-photon-session-runner-nightly"
  depends_on "rusty-photon-sky-survey-camera-nightly"
  depends_on "rusty-photon-star-adventurer-gti-nightly"
  depends_on "rusty-photon-ui-htmx-nightly"
  depends_on "rusty-photon-zwo-camera-nightly"
  depends_on "rusty-photon-zwo-focuser-nightly"

  conflicts_with "rusty-photon",
    because: "both channels install the same service family"

  def install
    prefix.install "SHA256SUMS.txt"
  end

  test do
    assert_path_exists prefix/"SHA256SUMS.txt"
  end
end
