# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPaFalconRotatorNightly < Formula
  desc "ASCOM Alpaca driver for Pegasus Astro Falcon Rotator (firmware >= 1.3)"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.20260716.g5f506ab"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-pa-falcon-rotator-0.1.0+nightly.20260716.g5f506ab-aarch64-apple-darwin.tar.gz"
  sha256 "96ea88beb0bea87ef7da4c4747c91cdb9f56e29e952a85cf05a5e7f2d55ffe6d"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-pa-falcon-rotator",
    because: "both channels install the same rusty-photon-pa-falcon-rotator binary"

  def install
    bin.install "rusty-photon-pa-falcon-rotator"
  end

  service do
    run [opt_bin/"rusty-photon-pa-falcon-rotator"]
    keep_alive true
    log_path var/"log/rusty-photon-pa-falcon-rotator.log"
    error_log_path var/"log/rusty-photon-pa-falcon-rotator.log"
  end

  test do
    assert_match "pa-falcon-rotator", shell_output("#{bin}/rusty-photon-pa-falcon-rotator --help")
  end
end
