# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonSkySurveyCameraNightly < Formula
  desc "ASCOM Alpaca Camera simulator backed by NASA SkyView"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.20260714.g6b8a1c6"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-sky-survey-camera-0.1.0+nightly.20260714.g6b8a1c6-aarch64-apple-darwin.tar.gz"
  sha256 "e6cc4f80efbc664e7b8af7e9978cdb11907d05bf701d82393c948055d71b0dd0"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-sky-survey-camera",
    because: "both channels install the same rusty-photon-sky-survey-camera binary"

  def install
    bin.install "rusty-photon-sky-survey-camera"
  end

  service do
    run [opt_bin/"rusty-photon-sky-survey-camera"]
    keep_alive true
    log_path var/"log/rusty-photon-sky-survey-camera.log"
    error_log_path var/"log/rusty-photon-sky-survey-camera.log"
  end

  test do
    assert_match "sky-survey-camera", shell_output("#{bin}/rusty-photon-sky-survey-camera --help")
  end
end
