# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPlanetariumBridgeNightly < Formula
  desc "Virtual ASCOM Alpaca Telescope: planetarium Align gestures become paused rusty-photon targets"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607311702.gb63451b"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-planetarium-bridge-0.1.0+nightly.202607311702.gb63451b-aarch64-apple-darwin.tar.gz"
  sha256 "ee220f4c213e78c91762f7135b312a090b99eac3501531ff406ac6e036b23d5f"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-planetarium-bridge",
    because: "both channels install the same rusty-photon-planetarium-bridge binary"

  def install
    bin.install "rusty-photon-planetarium-bridge"
  end

  service do
    run [opt_bin/"rusty-photon-planetarium-bridge"]
    keep_alive true
    log_path var/"log/rusty-photon-planetarium-bridge.log"
    error_log_path var/"log/rusty-photon-planetarium-bridge.log"
  end

  test do
    assert_match "planetarium-bridge", shell_output("#{bin}/rusty-photon-planetarium-bridge --help")
  end
end
