# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonQhyFocuserNightly < Formula
  desc "ASCOM Alpaca driver for QHY Q-Focuser (EAF)"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202608150534.gf59024d"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-qhy-focuser-0.1.0+nightly.202608150534.gf59024d-aarch64-apple-darwin.tar.gz"
  sha256 "f5f3f8312a9a66f306ed92c8ffb64c5899ed176a52368752d8902b3756b0e5e4"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-qhy-focuser",
    because: "both channels install the same rusty-photon-qhy-focuser binary"

  def install
    bin.install "rusty-photon-qhy-focuser"
  end

  service do
    run [opt_bin/"rusty-photon-qhy-focuser"]
    keep_alive true
    log_path var/"log/rusty-photon-qhy-focuser.log"
    error_log_path var/"log/rusty-photon-qhy-focuser.log"
  end

  test do
    assert_match "qhy-focuser", shell_output("#{bin}/rusty-photon-qhy-focuser --help")
  end
end
