# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPaFalconRotatorNightly < Formula
  desc "ASCOM Alpaca driver for Pegasus Astro Falcon Rotator (firmware >= 1.3)"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607311702.gb63451b"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-pa-falcon-rotator-0.1.0+nightly.202607311702.gb63451b-aarch64-apple-darwin.tar.gz"
  sha256 "3959410b86a8f2373fd7e89d050f352d6a76c769f672c23312046647ffaf1a08"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-pa-falcon-rotator",
    because: "both channels install the same rusty-photon-pa-falcon-rotator binary"

  def install
    bin.install "rusty-photon-pa-falcon-rotator"
  end

  service do
    run [opt_bin/"rusty-photon-pa-falcon-rotator"]
    keep_alive true
    log_path var/"log/rusty-photon-pa-falcon-rotator.log"
    error_log_path var/"log/rusty-photon-pa-falcon-rotator.log"
  end

  test do
    assert_match "pa-falcon-rotator", shell_output("#{bin}/rusty-photon-pa-falcon-rotator --help")
  end
end
