# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonCalibratorFlatsNightly < Formula
  desc "Calibrator flat field orchestrator - iterative exposure optimization with CoverCalibrator control"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202608120622.ged3a33c"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-calibrator-flats-0.1.0+nightly.202608120622.ged3a33c-aarch64-apple-darwin.tar.gz"
  sha256 "b5a4c76defe1d115fd7927175eae0c1ef3b42b3745bd120322327632d394e570"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-calibrator-flats",
    because: "both channels install the same rusty-photon-calibrator-flats binary"

  def install
    bin.install "rusty-photon-calibrator-flats"
  end

  service do
    run [opt_bin/"rusty-photon-calibrator-flats"]
    keep_alive true
    log_path var/"log/rusty-photon-calibrator-flats.log"
    error_log_path var/"log/rusty-photon-calibrator-flats.log"
  end

  test do
    assert_match "calibrator-flats", shell_output("#{bin}/rusty-photon-calibrator-flats --help")
  end
end
