# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPaScopsOagNightly < Formula
  desc "ASCOM Alpaca driver for the Pegasus Astro Scops OAG focuser"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607201851.g672cbab"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-pa-scops-oag-0.1.0+nightly.202607201851.g672cbab-aarch64-apple-darwin.tar.gz"
  sha256 "e9222ad958c5630dbd8666bd5625f03f71aa02f22c189f6fb3784cfe28c0a905"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-pa-scops-oag",
    because: "both channels install the same rusty-photon-pa-scops-oag binary"

  def install
    bin.install "rusty-photon-pa-scops-oag"
  end

  service do
    run [opt_bin/"rusty-photon-pa-scops-oag"]
    keep_alive true
    log_path var/"log/rusty-photon-pa-scops-oag.log"
    error_log_path var/"log/rusty-photon-pa-scops-oag.log"
  end

  test do
    assert_match "pa-scops-oag", shell_output("#{bin}/rusty-photon-pa-scops-oag --help")
  end
end
