# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonFilemonitorNightly < Formula
  desc "File monitoring service for Rusty Photon"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202608070613.g43089e5"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-filemonitor-0.1.0+nightly.202608070613.g43089e5-aarch64-apple-darwin.tar.gz"
  sha256 "c4e4ffe2b1cff74a7ded63fdcb3f7a5765c9431fe740bd06da301843a30c48f9"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-filemonitor",
    because: "both channels install the same rusty-photon-filemonitor binary"

  def install
    bin.install "rusty-photon-filemonitor"
  end

  service do
    run [opt_bin/"rusty-photon-filemonitor"]
    keep_alive true
    log_path var/"log/rusty-photon-filemonitor.log"
    error_log_path var/"log/rusty-photon-filemonitor.log"
  end

  test do
    assert_match "filemonitor", shell_output("#{bin}/rusty-photon-filemonitor --help")
  end
end
