# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonCalibratorFlatsNightly < Formula
  desc "Calibrator flat field orchestrator - iterative exposure optimization with CoverCalibrator control"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607200814.g547f38f"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-calibrator-flats-0.1.0+nightly.202607200814.g547f38f-aarch64-apple-darwin.tar.gz"
  sha256 "31d3e05f577c5b09d0d4166e2ff4fcbb042919b91e6842bae2059debf5a0dad7"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-calibrator-flats",
    because: "both channels install the same rusty-photon-calibrator-flats binary"

  def install
    bin.install "rusty-photon-calibrator-flats"
  end

  service do
    run [opt_bin/"rusty-photon-calibrator-flats"]
    keep_alive true
    log_path var/"log/rusty-photon-calibrator-flats.log"
    error_log_path var/"log/rusty-photon-calibrator-flats.log"
  end

  test do
    assert_match "calibrator-flats", shell_output("#{bin}/rusty-photon-calibrator-flats --help")
  end
end
