# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonSentinelNightly < Formula
  desc "Observatory monitoring and notification service"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.20260715.gb72dc63"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-sentinel-0.1.0+nightly.20260715.gb72dc63-aarch64-apple-darwin.tar.gz"
  sha256 "e5f066a783cb2f028d8e82ce7f1e7f3e653563c2dd9398b2c3a1ecda5c0f662b"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-sentinel",
    because: "both channels install the same rusty-photon-sentinel binary"

  def install
    bin.install "rusty-photon-sentinel"
  end

  service do
    run [opt_bin/"rusty-photon-sentinel"]
    keep_alive true
    log_path var/"log/rusty-photon-sentinel.log"
    error_log_path var/"log/rusty-photon-sentinel.log"
  end

  test do
    assert_match "sentinel", shell_output("#{bin}/rusty-photon-sentinel --help")
  end
end
