# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonSentinelNightly < Formula
  desc "Observatory monitoring and notification service"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.20260717.g28dd149"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-sentinel-0.1.0+nightly.20260717.g28dd149-aarch64-apple-darwin.tar.gz"
  sha256 "9eaa4351a6810abdc240a6e0ced86ec2813d5dbf1d97e0333f1ac48ff947410e"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-sentinel",
    because: "both channels install the same rusty-photon-sentinel binary"

  def install
    bin.install "rusty-photon-sentinel"
  end

  service do
    run [opt_bin/"rusty-photon-sentinel"]
    keep_alive true
    log_path var/"log/rusty-photon-sentinel.log"
    error_log_path var/"log/rusty-photon-sentinel.log"
  end

  test do
    assert_match "sentinel", shell_output("#{bin}/rusty-photon-sentinel --help")
  end
end
