# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPhd2GuiderNightly < Formula
  desc "PHD2 guider client library and service for Rusty Photon"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.20260718.g6f89442"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-phd2-guider-0.1.0+nightly.20260718.g6f89442-aarch64-apple-darwin.tar.gz"
  sha256 "c408bee152561bb86766607d38e96509b884212ac1ecd129e69e7fc8d180474a"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-phd2-guider",
    because: "both channels install the same rusty-photon-phd2-guider binary"

  def install
    bin.install "rusty-photon-phd2-guider"
  end

  service do
    run [opt_bin/"rusty-photon-phd2-guider"]
    keep_alive true
    log_path var/"log/rusty-photon-phd2-guider.log"
    error_log_path var/"log/rusty-photon-phd2-guider.log"
  end

  test do
    assert_match "phd2-guider", shell_output("#{bin}/rusty-photon-phd2-guider --help")
  end
end
