# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPaFalconRotatorNightly < Formula
  desc "ASCOM Alpaca driver for Pegasus Astro Falcon Rotator (firmware >= 1.3)"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607191903.g11683bc"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-pa-falcon-rotator-0.1.0+nightly.202607191903.g11683bc-aarch64-apple-darwin.tar.gz"
  sha256 "32b34af4730b3a1a7e332df7d6ba467b29a96a5a48bd8e3a1b3a11fbe4995d85"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-pa-falcon-rotator",
    because: "both channels install the same rusty-photon-pa-falcon-rotator binary"

  def install
    bin.install "rusty-photon-pa-falcon-rotator"
  end

  service do
    run [opt_bin/"rusty-photon-pa-falcon-rotator"]
    keep_alive true
    log_path var/"log/rusty-photon-pa-falcon-rotator.log"
    error_log_path var/"log/rusty-photon-pa-falcon-rotator.log"
  end

  test do
    assert_match "pa-falcon-rotator", shell_output("#{bin}/rusty-photon-pa-falcon-rotator --help")
  end
end
