# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonQhyCameraNightly < Formula
  desc "ASCOM Alpaca Camera (+ FilterWheel) driver for QHYCCD hardware"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607312329.g1c69cda"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-qhy-camera-0.1.0+nightly.202607312329.g1c69cda-aarch64-apple-darwin.tar.gz"
  sha256 "5a2cab9aee1e9eac791a4c862efb415133e0f203a9a6cec0cfdf9d275e3d0533"

  depends_on :macos
  depends_on arch: :arm64
  depends_on "libusb"

  conflicts_with "rusty-photon-qhy-camera",
    because: "both channels install the same rusty-photon-qhy-camera binary"

  def install
    bin.install "rusty-photon-qhy-camera"
  end

  service do
    run [opt_bin/"rusty-photon-qhy-camera"]
    keep_alive true
    log_path var/"log/rusty-photon-qhy-camera.log"
    error_log_path var/"log/rusty-photon-qhy-camera.log"
  end

  def caveats
    <<~EOS
      QHYCCD's proprietary SDK is linked statically; nothing to install.
      Caveat: a factory-fresh ("cold") QHY camera needs a one-time firmware
      upload that this build does not yet perform on macOS — connect a
      camera that has been used before (e.g. flashed on a Linux host), or
      see docs/packaging-macos.md in the rusty-photon repo.
    EOS
  end

  test do
    assert_match "qhy-camera", shell_output("#{bin}/rusty-photon-qhy-camera --help")
  end
end
