# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPpbaDriverNightly < Formula
  desc "ASCOM Alpaca driver for Pegasus Astro Pocket Powerbox Advance Gen2"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202608120622.ged3a33c"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-ppba-driver-0.1.0+nightly.202608120622.ged3a33c-aarch64-apple-darwin.tar.gz"
  sha256 "b61f4c968bc52f95c69a048955eb31bfb1a90443464d7e0c0e427b53cdb0c763"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-ppba-driver",
    because: "both channels install the same rusty-photon-ppba-driver binary"

  def install
    bin.install "rusty-photon-ppba-driver"
  end

  service do
    run [opt_bin/"rusty-photon-ppba-driver"]
    keep_alive true
    log_path var/"log/rusty-photon-ppba-driver.log"
    error_log_path var/"log/rusty-photon-ppba-driver.log"
  end

  test do
    assert_match "ppba-driver", shell_output("#{bin}/rusty-photon-ppba-driver --help")
  end
end
