# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPaScopsOagNightly < Formula
  desc "ASCOM Alpaca driver for the Pegasus Astro Scops OAG focuser"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.20260718.g6f89442"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-pa-scops-oag-0.1.0+nightly.20260718.g6f89442-aarch64-apple-darwin.tar.gz"
  sha256 "da5159b48439111c3ad31a1ae3e15c49c49813f0a7a00290c217ee6ed9c6545c"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-pa-scops-oag",
    because: "both channels install the same rusty-photon-pa-scops-oag binary"

  def install
    bin.install "rusty-photon-pa-scops-oag"
  end

  service do
    run [opt_bin/"rusty-photon-pa-scops-oag"]
    keep_alive true
    log_path var/"log/rusty-photon-pa-scops-oag.log"
    error_log_path var/"log/rusty-photon-pa-scops-oag.log"
  end

  test do
    assert_match "pa-scops-oag", shell_output("#{bin}/rusty-photon-pa-scops-oag --help")
  end
end
