# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonStarAdventurerGtiNightly < Formula
  desc "ASCOM Alpaca driver for Sky-Watcher Star Adventurer GTi GEM"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.20260718.g338bd8d"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-star-adventurer-gti-0.1.0+nightly.20260718.g338bd8d-aarch64-apple-darwin.tar.gz"
  sha256 "433dbe1930ba12406b7cfe29cdf02d3987a67a9bcdc9fbc107e4aa8d18c548de"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-star-adventurer-gti",
    because: "both channels install the same rusty-photon-star-adventurer-gti binary"

  def install
    bin.install "rusty-photon-star-adventurer-gti"
  end

  service do
    run [opt_bin/"rusty-photon-star-adventurer-gti"]
    keep_alive true
    log_path var/"log/rusty-photon-star-adventurer-gti.log"
    error_log_path var/"log/rusty-photon-star-adventurer-gti.log"
  end

  test do
    assert_match "star-adventurer-gti", shell_output("#{bin}/rusty-photon-star-adventurer-gti --help")
  end
end
