# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonZwoFocuserNightly < Formula
  desc "ASCOM Alpaca Focuser driver for the ZWO EAF"
  homepage "https://github.com/ivonnyssen/rusty-photon"
  version "0.1.0+nightly.202607201851.g672cbab"
  license all_of: [{ any_of: ["MIT", "Apache-2.0"] }, "MIT"]
  url "https://github.com/ivonnyssen/rusty-photon/releases/download/nightly/rusty-photon-zwo-focuser-0.1.0+nightly.202607201851.g672cbab-aarch64-apple-darwin.tar.gz"
  sha256 "2ea53afcc5966a187fd4469ee84120540b01c945ce12cdb6e83587a736ff8b78"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-zwo-focuser",
    because: "both channels install the same rusty-photon-zwo-focuser binary"

  def install
    bin.install "rusty-photon-zwo-focuser"
    lib.install Dir["lib/*.dylib"]
    doc.install "ZWO-SDK-LICENSE.txt"
  end

  service do
    run [opt_bin/"rusty-photon-zwo-focuser"]
    keep_alive true
    log_path var/"log/rusty-photon-zwo-focuser.log"
    error_log_path var/"log/rusty-photon-zwo-focuser.log"
  end

  def caveats
    <<~EOS
      EAF discovery uses macOS HID APIs that need a privacy grant for the
      service binary; under `brew services` without one the service blocks
      at startup without serving. Grant it under System Settings → Privacy
      & Security (or run the binary once in a terminal), then restart the
      service. Details: docs/packaging-macos.md in the rusty-photon repo.
    EOS
  end

  test do
    assert_match "zwo-focuser", shell_output("#{bin}/rusty-photon-zwo-focuser --help")
  end
end
