# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonRpNightly < Formula
  desc "Rusty Photon main application - equipment gateway, event bus, and safety enforcer"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202608030838.g77f8320"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-rp-0.1.0+nightly.202608030838.g77f8320-aarch64-apple-darwin.tar.gz"
  sha256 "f25636cb484a9c9ee921c825334e37b4f2f6989a1eb2cd14f2dac1ea2363cf32"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-rp",
    because: "both channels install the same rusty-photon-rp binary"

  def install
    bin.install "rusty-photon-rp"
  end

  service do
    run [opt_bin/"rusty-photon-rp"]
    keep_alive true
    log_path var/"log/rusty-photon-rp.log"
    error_log_path var/"log/rusty-photon-rp.log"
  end

  test do
    assert_match "rp", shell_output("#{bin}/rusty-photon-rp --help")
  end
end
